name: CI - RPG Project

on:
  push:
    branches: [ dev ]

permissions:
  contents: write  

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.15'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Clean pycache
      run: |
        find . -name "*.pyc" -delete
        find . -name "__pycache__" -type d -exec rm -r {} +

    - name: Run tests and handle result
      run: |
        set -e

        if ! pytest; then
          echo "❌ Tests failed"

          COMMIT_NAME=$(git log -1 --pretty=format:"%s" | tr ' ' '_' | tr -dc '[:alnum:]_-')
          BRANCH_NAME="failures/${COMMIT_NAME}"
          echo "Creating branch $BRANCH_NAME"

          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          # Créer et pousser la branche failure
          git checkout -b "$BRANCH_NAME"
          git push origin "$BRANCH_NAME"

          # Réinitialiser dev vers main
          git checkout dev
          git reset --hard origin/main
          git push --force origin dev

          exit 1
        else
          echo "✅ Tests passed — merging dev → main"

          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git fetch origin dev
          git fetch origin main
          git checkout main

          git merge origin/dev --strategy=recursive -X theirs --allow-unrelated-histories --no-edit
          git push origin main
        fi