name: RPG CI/CD Pipeline

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Run tests
      id: test_step
      run: |
        pytest tests/ -v --cov=src --cov-report=term-missing
      continue-on-error: true
    
    - name: Handle test success
      if: steps.test_step.outcome == 'success'
      run: |
        echo "Tests passed - Merging to main"
        git config --global user.name 'CI Bot'
        git config --global user.email 'ci-bot@example.com'
        git fetch origin main
        git checkout main
        git merge --ff-only origin/dev
        git push origin main
    
    - name: Handle test failure
      if: steps.test_step.outcome == 'failure'
      run: |
        echo "Tests failed - Creating failure branch"
        FAILURE_BRANCH="failures/$(date +%Y%m%d-%H%M%S)-$(git rev-parse --short HEAD)"
        git config --global user.name 'CI Bot'
        git config --global user.email 'ci-bot@example.com'
        git checkout -b $FAILURE_BRANCH
        git push origin $FAILURE_BRANCH
        git checkout dev
        git reset --hard HEAD~1
        git push --force origin dev
        exit 1